apiVersion: v1
kind: Namespace
metadata:
  name: grpc-calculator-nold
---
apiVersion: v1
kind: Service
metadata:
  name: addition
  namespace: grpc-calculator-nold
spec:
  ports:
  - name: grpc
    port: 5001
    targetPort: 80  
  selector:
    app: addition
  type: ClusterIP        
---
apiVersion: v1
kind: Service
metadata:
  name: substraction
  namespace: grpc-calculator-nold
spec:
  ports:
  - name: grpc
    port: 5004
    targetPort: 80  
  selector:
    app: substraction
  type: ClusterIP    
---
apiVersion: v1
kind: Service
metadata:
  name: division
  namespace: grpc-calculator-nold
spec:
  ports:
  - name: grpc
    port: 5002
    targetPort: 80
  selector:
    app: division
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: percentage
  namespace: grpc-calculator-nold
spec:
  ports:
  - name: grpc
    port: 5005
    targetPort: 80
  selector:
    app: percentage
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: multiplication
  namespace: grpc-calculator-nold
spec:
  ports:
  - name: grpc
    port: 5003
    targetPort: 80
  selector:
    app: multiplication
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: addition
    app.kubernetes.io/part-of: calculator
    app.kubernetes.io/version: v9  
  name: addition
  namespace: grpc-calculator-nold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addition
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: addition      
    spec:
      containers:      
      - name: addition
        image: stephaneey/calcadd:dev        
        ports:
        - containerPort: 5001
          name: grpc        
        resources:
          requests:
            cpu: 10m
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: division
    app.kubernetes.io/part-of: calculator
    app.kubernetes.io/version: v9
  name: division
  namespace: grpc-calculator-nold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: division
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: division      
    spec:
      containers:      
      - name: division
        image: stephaneey/calcdivide:dev        
        ports:
        - containerPort: 5002
          name: grpc        
        resources:
          requests:
            cpu: 10m
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: substraction
    app.kubernetes.io/part-of: calculator
    app.kubernetes.io/version: v9
  name: substraction
  namespace: grpc-calculator-nold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: substraction
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: substraction      
    spec:
      containers:      
      - name: substraction
        image: stephaneey/calcsubstract:dev
        imagePullPolicy: Always 
        ports:
        - containerPort: 5004
          name: grpc   
        resources:
          requests:
            cpu: 10m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: multiplication
    app.kubernetes.io/part-of: calculator
    app.kubernetes.io/version: v9
  name: multiplication
  namespace: grpc-calculator-nold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multiplication
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: multiplication      
    spec:
      containers:      
      - name: multiplication
        image: stephaneey/calcmultiply:dev        
        ports:
        - containerPort: 5003
          name: grpc        
        resources:
          requests:
            cpu: 10m
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: percentage
    app.kubernetes.io/part-of: calculator
    app.kubernetes.io/version: v9
  name: percentage
  namespace: grpc-calculator-nold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: percentage
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: percentage      
    spec:
      containers:      
      - name: percentage
        image: stephaneey/calcpercentage:dev
        imagePullPolicy: Always
        env:                
        - name: DivisionEndpoint
          value: http://division.grpc-calculator:5002
        - name: MultiplicationEndpoint
          value: http://multiplication.grpc-calculator:5003               
        ports:
        - containerPort: 5005
          name: grpc        
        resources:
          requests:
            cpu: 10m
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mathfanboy
    app.kubernetes.io/part-of: calculator
    app.kubernetes.io/version: v9
  name: mathfanboy
  namespace: grpc-calculator-nold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathfanboy
  template:
    metadata:
      labels:
        app: mathfanboy      
    spec:
      containers:
      - name: mathfanboy       
        image: stephaneey/mathfanboy:dev
        imagePullPolicy: Always
        env:        
        - name: AdditionEndpoint
          value: http://addition.grpc-calculator-nold:5001
        - name: DivisionEndpoint
          value: http://division.grpc-calculator-nold:5002
        - name: MultiplicationEndpoint
          value: http://multiplication.grpc-calculator-nold:5003
        - name: SubstractionEndpoint
          value: http://substraction.grpc-calculator-nold:5004    
        - name: PercentageEndpoint
          value: http://percentage.grpc-calculator-nold:5005          
      