apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-api-client
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-api-client
  labels:
    app: grpc-api-client
    service: grpc-api-client
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: grpc-api-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-api-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-api-client
      version: v1
  template:
    metadata:
      labels:
        app: grpc-api-client
        version: v1
    spec:
      serviceAccountName: grpc-api-client
      containers:
      - image: docker.io/karabasosman/grcp-api-client:latest
        imagePullPolicy: Always
        name: grpc-api-client
        env:
        - name: AdditionEndpoint
          value: "http://grpc-demo-svc.backend:5001"
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-api-client-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - grpc-api-client-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: grpc-api-client.default.svc.cluster.local