apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-demo-svc
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-demo-svc
  labels:
    app: grpc-demo-svc
    service: grpc-demo-svc
spec:
  ports:
  - name: grpc
    port: 5001
    targetPort: 5001
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: grpc-demo-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-demo-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-demo-svc
      version: v1
  template:
    metadata:
      labels:
        app: grpc-demo-svc
        version: v1
    spec:
      serviceAccountName: grpc-demo-svc
      containers:
      - image: docker.io/karabasosman/grpc-demo-svc:mix
        imagePullPolicy: Always
        name: grpc-demo-svc
        ports:
        - containerPort: 80
        - containerPort: 5001